version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Run Test Cases
          command: npm run test
